---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: egg-beach
spec:
  encryptedData:
    .dockerconfigjson: AgCVSbjKdQ0JtCN+6El3AB91N7vUOwYpc1N2xfxIixjKHI5ZEOxiZy73dtf7RSfH+I/gVR+FBzr7vMSuwvWQiplN50jwRrFyfRNKzAFC0zuWZ9/d+w3UuBhOcYcqlsxXTopfUjc/yDDf2DlW6gj0ossS9NGIODKrAko65wtdpKXZsgxiu3XkUbwiqyNoywtH2KWwGIVvMyQwl5Q6V6eR74o/HUEViFQZo8wMroB2NV507ds0Mwev+sqympbzCvND2FBhmmVPrfBFq8trbUiEP5YN3TKxWnYkp3sRGXRMzef2V8m0PdjS4CLBbsO72VrfGMaHKNiQujh7yMD1eWFWgn4O1ht1g+zgbQrlbCSlV4xAOakfY8UuWQve0hlDP1JpcDxvNE017cu6yju64y5IzYKbsALgnCCVD7cw+c3bTS6Ai+OUUEvxpdj1wDYl6kukCmkpoTlpJRAJnudybD5E4N9i9AQdBThV/oEmGnWmV/r4jk/q+COLcXhUZW5wnezaEb3YiiDtLhHq+TolyAhTiwre4lElxrJdvkvGoFbBpKq7W2YDktohpQwZOOoM0rcft+pJ0LgOOH7ZLEqpAhcf9n2xmhvL4aSLgemJJ9u/Idt6oBb8+5uXLJ6DjSj6l7g8Hg+BUAzHhI9vHoHPCUiEnEJYFscKqv2ldAjyKFnPTjIBMPeEfCYhqRhe++OKAKooi7VZfsi4bdMvEx1ftn+lg7Ds+lt1OldZuGAaX3gZq/z8+zaUOWkGrzKlU0YUn6hqpqur9fuUzpsefbwMqged9RWFaf8qahZd1OZ4p1wed0aWra9lBpEvGi2K3ppaqz6Zi34qNIJ/Kt7sfV35LIDehZdgdQ3w39h+chRn/X9jtR/s/+O0pNpqzQTNVTxYKnvrTh21Gg3TwOf0SxsBtJzUqrhJE4gDTx1BFxMMjNgf4FnUyHrMEW2x0VFiMA==
  template:
    metadata:
      name: ghcr-pull
      namespace: egg-beach
    type: kubernetes.io/dockerconfigjson
